project:
  type: website
  output-dir: _site

website:
  title: "Student Data Science Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Resume"
        href: projects/resume.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
